"use client";

import { useState } from "react";
import { ask, AskResponse, Evidence } from "../../../lib/api";
import EvidenceCard from "./EvidenceCard";

const SUGGESTIONS = ["What is the chronological sequence of events?", "What claims are made, and what footage supports them?", "Who is mentioned or involved in the incident?"];

export default function AskPanel({ investigationId, selectedVideoIds, onPlayEvidence }: { investigationId: string; selectedVideoIds: string[]; onPlayEvidence: (evidence: Evidence) => void }) {
  const [question, setQuestion] = useState("");
  const [asking, setAsking] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AskResponse | null>(null);
  async function handleSubmit(event: React.FormEvent) { event.preventDefault(); if (!question.trim() || selectedVideoIds.length === 0) return; setAsking(true); setError(null); try { setResult(await ask(investigationId, question.trim(), selectedVideoIds)); } catch (err) { setError(err instanceof Error ? err.message : "Failed to get an answer"); } finally { setAsking(false); } }
  return <section className="rounded-3xl border border-white/80 bg-white/70 p-6 shadow-[0_20px_60px_-40px_rgba(15,23,42,0.45)] backdrop-blur-xl dark:border-white/5 dark:bg-zinc-950/65"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-700 dark:text-blue-400">Evidence assistant</p><h2 className="mt-1 text-lg font-semibold">Ask this case</h2><p className="mt-1 text-sm text-slate-500 dark:text-zinc-400">Answers are constrained to the selected footage and return playable evidence ranges.</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600 dark:bg-zinc-800 dark:text-zinc-300">{selectedVideoIds.length} source{selectedVideoIds.length === 1 ? "" : "s"}</span></div><form onSubmit={handleSubmit} className="mt-5"><textarea value={question} onChange={(event) => setQuestion(event.target.value)} rows={3} placeholder="Ask a specific question about the evidence…" className="w-full rounded-2xl border border-slate-200 bg-white/80 px-4 py-3 text-sm outline-none transition focus:border-blue-600 focus:ring-2 focus:ring-blue-100 dark:border-zinc-700 dark:focus:ring-blue-950" /><div className="mt-3 flex flex-wrap gap-2">{SUGGESTIONS.map((suggestion) => <button key={suggestion} type="button" onClick={() => setQuestion(suggestion)} className="rounded-full border border-white/80 bg-white/70 px-3 py-1.5 text-xs text-slate-600 transition hover:-translate-y-0.5 hover:border-blue-200 hover:text-blue-700 hover:shadow-sm dark:border-white/5 dark:bg-zinc-900 dark:text-zinc-300">{suggestion}</button>)}</div><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-slate-500 dark:text-zinc-400">{selectedVideoIds.length === 0 ? "Select at least one ready source to ask a question." : ""}</p><button type="submit" disabled={asking || !question.trim() || selectedVideoIds.length === 0} className="rounded-full bg-gradient-to-r from-blue-600 to-indigo-700 px-5 py-2.5 text-sm font-medium text-white shadow-lg shadow-blue-500/25 transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50">{asking ? "Reviewing evidence…" : "Ask evidence"}</button></div>{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}</form>{result && <div className="mt-6 border-t border-slate-200 pt-5 dark:border-zinc-800"><h3 className="text-sm font-semibold">Evidence-grounded answer</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700 dark:text-zinc-300">{result.answer}</p>{result.evidence.length > 0 && <div className="mt-5"><h4 className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-zinc-400">Supporting clips</h4><div className="mt-2 space-y-2">{result.evidence.map((evidence, index) => <EvidenceCard key={`${evidence.video_id}-${index}`} evidence={evidence} onPlay={onPlayEvidence} />)}</div></div>}</div>}</section>;
}